export { default as Aboutus } from './aboutus';
export { default as Alerts } from './alerts';
export { default as ContactUs } from './ContactUs';
export { default as Faq } from './faq';
export { default as Forecast } from './forecast';
export { default as Home } from './home';
export { default as News } from './news';
export { default as Privacy } from './Privacy';
export { default as Terms } from './Terms';
